/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutsRouteImport } from './routes/_layouts'
import { Route as LayoutsProfileRouteImport } from './routes/_layouts/profile'
import { Route as LayoutsNavMenuRouteImport } from './routes/_layouts/nav-menu'
import { Route as LayoutsGlobalSearchRouteImport } from './routes/_layouts/global-search'
import { Route as LayoutsChartRouteImport } from './routes/_layouts/chart'

const ToolbarLazyRouteImport = createFileRoute('/toolbar')()
const FooterLazyRouteImport = createFileRoute('/footer')()
const LayoutsIndexLazyRouteImport = createFileRoute('/_layouts/')()
const LayoutsWatchlistLazyRouteImport = createFileRoute('/_layouts/watchlist')()
const LayoutsListLazyRouteImport = createFileRoute('/_layouts/list')()
const LayoutsAboutLazyRouteImport = createFileRoute('/_layouts/about')()

const ToolbarLazyRoute = ToolbarLazyRouteImport.update({
  id: '/toolbar',
  path: '/toolbar',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/toolbar.lazy').then((d) => d.Route))
const FooterLazyRoute = FooterLazyRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/footer.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsRoute = LayoutsRouteImport.update({
  id: '/_layouts',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutsIndexLazyRoute = LayoutsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutsRoute,
} as any).lazy(() =>
  import('./routes/_layouts/index.lazy').then((d) => d.Route),
)
const LayoutsWatchlistLazyRoute = LayoutsWatchlistLazyRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => LayoutsRoute,
} as any).lazy(() =>
  import('./routes/_layouts/watchlist.lazy').then((d) => d.Route),
)
const LayoutsListLazyRoute = LayoutsListLazyRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => LayoutsRoute,
} as any).lazy(() => import('./routes/_layouts/list.lazy').then((d) => d.Route))
const LayoutsAboutLazyRoute = LayoutsAboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutsRoute,
} as any).lazy(() =>
  import('./routes/_layouts/about.lazy').then((d) => d.Route),
)
const LayoutsProfileRoute = LayoutsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutsRoute,
} as any)
const LayoutsNavMenuRoute = LayoutsNavMenuRouteImport.update({
  id: '/nav-menu',
  path: '/nav-menu',
  getParentRoute: () => LayoutsRoute,
} as any)
const LayoutsGlobalSearchRoute = LayoutsGlobalSearchRouteImport.update({
  id: '/global-search',
  path: '/global-search',
  getParentRoute: () => LayoutsRoute,
} as any)
const LayoutsChartRoute = LayoutsChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => LayoutsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/footer': typeof FooterLazyRoute
  '/toolbar': typeof ToolbarLazyRoute
  '/chart': typeof LayoutsChartRoute
  '/global-search': typeof LayoutsGlobalSearchRoute
  '/nav-menu': typeof LayoutsNavMenuRoute
  '/profile': typeof LayoutsProfileRoute
  '/about': typeof LayoutsAboutLazyRoute
  '/list': typeof LayoutsListLazyRoute
  '/watchlist': typeof LayoutsWatchlistLazyRoute
  '/': typeof LayoutsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/footer': typeof FooterLazyRoute
  '/toolbar': typeof ToolbarLazyRoute
  '/chart': typeof LayoutsChartRoute
  '/global-search': typeof LayoutsGlobalSearchRoute
  '/nav-menu': typeof LayoutsNavMenuRoute
  '/profile': typeof LayoutsProfileRoute
  '/about': typeof LayoutsAboutLazyRoute
  '/list': typeof LayoutsListLazyRoute
  '/watchlist': typeof LayoutsWatchlistLazyRoute
  '/': typeof LayoutsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layouts': typeof LayoutsRouteWithChildren
  '/login': typeof LoginRoute
  '/footer': typeof FooterLazyRoute
  '/toolbar': typeof ToolbarLazyRoute
  '/_layouts/chart': typeof LayoutsChartRoute
  '/_layouts/global-search': typeof LayoutsGlobalSearchRoute
  '/_layouts/nav-menu': typeof LayoutsNavMenuRoute
  '/_layouts/profile': typeof LayoutsProfileRoute
  '/_layouts/about': typeof LayoutsAboutLazyRoute
  '/_layouts/list': typeof LayoutsListLazyRoute
  '/_layouts/watchlist': typeof LayoutsWatchlistLazyRoute
  '/_layouts/': typeof LayoutsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/footer'
    | '/toolbar'
    | '/chart'
    | '/global-search'
    | '/nav-menu'
    | '/profile'
    | '/about'
    | '/list'
    | '/watchlist'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/footer'
    | '/toolbar'
    | '/chart'
    | '/global-search'
    | '/nav-menu'
    | '/profile'
    | '/about'
    | '/list'
    | '/watchlist'
    | '/'
  id:
    | '__root__'
    | '/_layouts'
    | '/login'
    | '/footer'
    | '/toolbar'
    | '/_layouts/chart'
    | '/_layouts/global-search'
    | '/_layouts/nav-menu'
    | '/_layouts/profile'
    | '/_layouts/about'
    | '/_layouts/list'
    | '/_layouts/watchlist'
    | '/_layouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutsRoute: typeof LayoutsRouteWithChildren
  LoginRoute: typeof LoginRoute
  FooterLazyRoute: typeof FooterLazyRoute
  ToolbarLazyRoute: typeof ToolbarLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toolbar': {
      id: '/toolbar'
      path: '/toolbar'
      fullPath: '/toolbar'
      preLoaderRoute: typeof ToolbarLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer': {
      id: '/footer'
      path: '/footer'
      fullPath: '/footer'
      preLoaderRoute: typeof FooterLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layouts': {
      id: '/_layouts'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layouts/': {
      id: '/_layouts/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutsIndexLazyRouteImport
      parentRoute: typeof LayoutsRoute
    }
    '/_layouts/watchlist': {
      id: '/_layouts/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof LayoutsWatchlistLazyRouteImport
      parentRoute: typeof LayoutsRoute
    }
    '/_layouts/list': {
      id: '/_layouts/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof LayoutsListLazyRouteImport
      parentRoute: typeof LayoutsRoute
    }
    '/_layouts/about': {
      id: '/_layouts/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutsAboutLazyRouteImport
      parentRoute: typeof LayoutsRoute
    }
    '/_layouts/profile': {
      id: '/_layouts/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutsProfileRouteImport
      parentRoute: typeof LayoutsRoute
    }
    '/_layouts/nav-menu': {
      id: '/_layouts/nav-menu'
      path: '/nav-menu'
      fullPath: '/nav-menu'
      preLoaderRoute: typeof LayoutsNavMenuRouteImport
      parentRoute: typeof LayoutsRoute
    }
    '/_layouts/global-search': {
      id: '/_layouts/global-search'
      path: '/global-search'
      fullPath: '/global-search'
      preLoaderRoute: typeof LayoutsGlobalSearchRouteImport
      parentRoute: typeof LayoutsRoute
    }
    '/_layouts/chart': {
      id: '/_layouts/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof LayoutsChartRouteImport
      parentRoute: typeof LayoutsRoute
    }
  }
}

interface LayoutsRouteChildren {
  LayoutsChartRoute: typeof LayoutsChartRoute
  LayoutsGlobalSearchRoute: typeof LayoutsGlobalSearchRoute
  LayoutsNavMenuRoute: typeof LayoutsNavMenuRoute
  LayoutsProfileRoute: typeof LayoutsProfileRoute
  LayoutsAboutLazyRoute: typeof LayoutsAboutLazyRoute
  LayoutsListLazyRoute: typeof LayoutsListLazyRoute
  LayoutsWatchlistLazyRoute: typeof LayoutsWatchlistLazyRoute
  LayoutsIndexLazyRoute: typeof LayoutsIndexLazyRoute
}

const LayoutsRouteChildren: LayoutsRouteChildren = {
  LayoutsChartRoute: LayoutsChartRoute,
  LayoutsGlobalSearchRoute: LayoutsGlobalSearchRoute,
  LayoutsNavMenuRoute: LayoutsNavMenuRoute,
  LayoutsProfileRoute: LayoutsProfileRoute,
  LayoutsAboutLazyRoute: LayoutsAboutLazyRoute,
  LayoutsListLazyRoute: LayoutsListLazyRoute,
  LayoutsWatchlistLazyRoute: LayoutsWatchlistLazyRoute,
  LayoutsIndexLazyRoute: LayoutsIndexLazyRoute,
}

const LayoutsRouteWithChildren =
  LayoutsRoute._addFileChildren(LayoutsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutsRoute: LayoutsRouteWithChildren,
  LoginRoute: LoginRoute,
  FooterLazyRoute: FooterLazyRoute,
  ToolbarLazyRoute: ToolbarLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
